languageCode = "en"
languageName = "English"
weight = 1
title = "JustInTimeOps"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "My awesome website"
dateFormat = "2 January 2006"
author = { name = "Justin De Sio", image = "img/avatar.png", headline = "DevOps Engineer", bio = "Production Engineer at Cloud Temple.", links = [
    { github = "https://github.com/justin-de-sio" },
    { linkedin = "https://www.linkedin.com/in/justin-de-sio/" },
] }
