#!/bin/bash

export NEW_NAME="Justin De Sio"
export NEW_EMAIL="desio.j@live.fr"

git filter-branch --env-filter '
if [ "$GIT_COMMITTER_EMAIL" != "$NEW_EMAIL" ] || [ "$GIT_AUTHOR_EMAIL" != "$NEW_EMAIL" ]; then
    export GIT_COMMITTER_NAME="$NEW_NAME"
    export GIT_COMMITTER_EMAIL="$NEW_EMAIL"
    export GIT_AUTHOR_NAME="$NEW_NAME"
    export GIT_AUTHOR_EMAIL="$NEW_EMAIL"
fi
' --tag-name-filter cat -- --branches --tags
